name: CI

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: 'us-east-2'

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Package app
        run: tar -czf ./app.tgz ./app
      - name: Push app to AWS S3
        run: aws s3 cp ./app.tgz ${{ secrets.AWS_CODE_BUCKET }}

# aws deploy create-deployment \
#   --application-name SimpleDemoApp \
#   --deployment-config-name CodeDeployDefault.OneAtATime \
#   --deployment-group-name SimpleDemoDG \
#   --s3-location bucket=bucket-name,bundleType=zip,key=samples/latest/SampleApp_Linux.zip
